/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.jinternals.FormularioProyectoJInternalFrame;
import vista.jinternals.FormularioEntregaJInternalFrame;
import vista.jinternals.AsignarDirectorJInternalFrame;
import vista.jinternals.ConsultarProyectosJInternalFrame;
import vista.jinternals.ReportesJInternalFrame;
import vista.jinternals.FormularioDirectoresJInternalFrame;

/**
 *
 * @author w8
 */
public class MDIAplicacion extends javax.swing.JFrame {

    FormularioProyectoJInternalFrame formularioProyectoJInternal;
    FormularioDirectoresJInternalFrame formularioDirectoresJInternal;
    FormularioEntregaJInternalFrame formularioEntregaJInternal;
    AsignarDirectorJInternalFrame formularioAsignarJInternal;
    ReportesJInternalFrame reportesJInternal;

    public MDIAplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenuIdeas = new javax.swing.JMenu();
        jMItemAdministrarIdeas = new javax.swing.JMenuItem();
        jMenuPropuestas = new javax.swing.JMenu();
        jMItemRevisionPropuesta = new javax.swing.JMenuItem();
        jMItemAdministrarPropuestas = new javax.swing.JMenuItem();
        jMenuAnteproyectos = new javax.swing.JMenu();
        jMItemRevisarAntep = new javax.swing.JMenuItem();
        jMItemAdministrarAntep = new javax.swing.JMenuItem();
        jMenuDirectores = new javax.swing.JMenu();
        jMItemAdministrarDirectores = new javax.swing.JMenuItem();
        jMenuProyectos = new javax.swing.JMenu();
        jMItemAdministrarProyectos = new javax.swing.JMenuItem();
        jMItemRegistrarEntrega = new javax.swing.JMenuItem();
        jMenuAsesorias = new javax.swing.JMenu();
        jMItemAdministrarAsesorias = new javax.swing.JMenuItem();
        jMenuSustentaciones = new javax.swing.JMenu();
        jMItemAdministrarSust = new javax.swing.JMenuItem();
        jMItemReservarEspacioSust = new javax.swing.JMenuItem();
        jMItemEjecutarSust = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuIdeas.setText("Ideas");
        jMenuIdeas.setPreferredSize(new java.awt.Dimension(45, 19));

        jMItemAdministrarIdeas.setText("Administrar");
        jMItemAdministrarIdeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAdministrarIdeasActionPerformed(evt);
            }
        });
        jMenuIdeas.add(jMItemAdministrarIdeas);

        menuBar.add(jMenuIdeas);

        jMenuPropuestas.setText("Propuestas");

        jMItemRevisionPropuesta.setText("Revisar");
        jMItemRevisionPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemRevisionPropuestaActionPerformed(evt);
            }
        });
        jMenuPropuestas.add(jMItemRevisionPropuesta);

        jMItemAdministrarPropuestas.setText("Administrar");
        jMItemAdministrarPropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAdministrarPropuestasActionPerformed(evt);
            }
        });
        jMenuPropuestas.add(jMItemAdministrarPropuestas);

        menuBar.add(jMenuPropuestas);

        jMenuAnteproyectos.setText("Anteproyectos");

        jMItemRevisarAntep.setText("Revisar");
        jMItemRevisarAntep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemRevisarAntepActionPerformed(evt);
            }
        });
        jMenuAnteproyectos.add(jMItemRevisarAntep);

        jMItemAdministrarAntep.setText("Administrar");
        jMItemAdministrarAntep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAdministrarAntepActionPerformed(evt);
            }
        });
        jMenuAnteproyectos.add(jMItemAdministrarAntep);

        menuBar.add(jMenuAnteproyectos);

        jMenuDirectores.setText("Directores");

        jMItemAdministrarDirectores.setText("Administrar");
        jMItemAdministrarDirectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAdministrarDirectoresActionPerformed(evt);
            }
        });
        jMenuDirectores.add(jMItemAdministrarDirectores);

        menuBar.add(jMenuDirectores);

        jMenuProyectos.setMnemonic('f');
        jMenuProyectos.setText("Proyectos");

        jMItemAdministrarProyectos.setText("Administrar");
        jMItemAdministrarProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAdministrarProyectosActionPerformed(evt);
            }
        });
        jMenuProyectos.add(jMItemAdministrarProyectos);

        jMItemRegistrarEntrega.setMnemonic('a');
        jMItemRegistrarEntrega.setText("Registrar entrega proyecto");
        jMItemRegistrarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemRegistrarEntregaActionPerformed(evt);
            }
        });
        jMenuProyectos.add(jMItemRegistrarEntrega);

        menuBar.add(jMenuProyectos);

        jMenuAsesorias.setText("Asesorias");

        jMItemAdministrarAsesorias.setText("Administrar");
        jMItemAdministrarAsesorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAdministrarAsesoriasActionPerformed(evt);
            }
        });
        jMenuAsesorias.add(jMItemAdministrarAsesorias);

        menuBar.add(jMenuAsesorias);

        jMenuSustentaciones.setText("Sustentaciones");

        jMItemAdministrarSust.setText("Administrar");
        jMItemAdministrarSust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAdministrarSustActionPerformed(evt);
            }
        });
        jMenuSustentaciones.add(jMItemAdministrarSust);

        jMItemReservarEspacioSust.setText("Reservar espacio");
        jMItemReservarEspacioSust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemReservarEspacioSustActionPerformed(evt);
            }
        });
        jMenuSustentaciones.add(jMItemReservarEspacioSust);

        jMItemEjecutarSust.setText("Ejecutar sustentacion");
        jMItemEjecutarSust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemEjecutarSustActionPerformed(evt);
            }
        });
        jMenuSustentaciones.add(jMItemEjecutarSust);

        menuBar.add(jMenuSustentaciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMItemRegistrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemRegistrarEntregaActionPerformed
        formularioEntregaJInternal = new FormularioEntregaJInternalFrame();
        desktopPane.add(formularioEntregaJInternal);
        formularioEntregaJInternal.show();
    }//GEN-LAST:event_jMItemRegistrarEntregaActionPerformed

    private void jMItemAdministrarProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAdministrarProyectosActionPerformed
        ConsultarProyectosJInternalFrame consultarProyectosJInternalFrame= new ConsultarProyectosJInternalFrame();
        desktopPane.add(consultarProyectosJInternalFrame);
        consultarProyectosJInternalFrame.setVisible(true);
    }//GEN-LAST:event_jMItemAdministrarProyectosActionPerformed

    private void jMItemAdministrarIdeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAdministrarIdeasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemAdministrarIdeasActionPerformed

    private void jMItemRevisionPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemRevisionPropuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemRevisionPropuestaActionPerformed

    private void jMItemAdministrarPropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAdministrarPropuestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemAdministrarPropuestasActionPerformed

    private void jMItemRevisarAntepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemRevisarAntepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemRevisarAntepActionPerformed

    private void jMItemAdministrarAntepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAdministrarAntepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemAdministrarAntepActionPerformed

    private void jMItemAdministrarDirectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAdministrarDirectoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemAdministrarDirectoresActionPerformed

    private void jMItemAdministrarAsesoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAdministrarAsesoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemAdministrarAsesoriasActionPerformed

    private void jMItemReservarEspacioSustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemReservarEspacioSustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemReservarEspacioSustActionPerformed

    private void jMItemEjecutarSustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemEjecutarSustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemEjecutarSustActionPerformed

    private void jMItemAdministrarSustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAdministrarSustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemAdministrarSustActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMItemAdministrarAntep;
    private javax.swing.JMenuItem jMItemAdministrarAsesorias;
    private javax.swing.JMenuItem jMItemAdministrarDirectores;
    private javax.swing.JMenuItem jMItemAdministrarIdeas;
    private javax.swing.JMenuItem jMItemAdministrarPropuestas;
    private javax.swing.JMenuItem jMItemAdministrarProyectos;
    private javax.swing.JMenuItem jMItemAdministrarSust;
    private javax.swing.JMenuItem jMItemEjecutarSust;
    private javax.swing.JMenuItem jMItemRegistrarEntrega;
    private javax.swing.JMenuItem jMItemReservarEspacioSust;
    private javax.swing.JMenuItem jMItemRevisarAntep;
    private javax.swing.JMenuItem jMItemRevisionPropuesta;
    private javax.swing.JMenu jMenuAnteproyectos;
    private javax.swing.JMenu jMenuAsesorias;
    private javax.swing.JMenu jMenuDirectores;
    private javax.swing.JMenu jMenuIdeas;
    private javax.swing.JMenu jMenuPropuestas;
    private javax.swing.JMenu jMenuProyectos;
    private javax.swing.JMenu jMenuSustentaciones;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
