/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.jinternals;

import controller.AvancesJpaController;
import controller.PropuestasJpaController;
import controller.RevisionesAvanceJpaController;
import controller.exceptions.IllegalOrphanException;
import controller.exceptions.NonexistentEntityException;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Avances;
import modelo.Propuestas;
import modelo.RevisionesAvance;

/**
 *
 * @author Puyo
 */
public class AvancesJInternalFrame extends javax.swing.JInternalFrame {
        Propuestas propuestas = new Propuestas();
        PropuestasJpaController propuestasjpa = new PropuestasJpaController(null);
        Avances avance = new Avances();
        AvancesJpaController avances = new AvancesJpaController(null);
        RevisionesAvance revision = new RevisionesAvance();
        RevisionesAvanceJpaController revisiones = new RevisionesAvanceJpaController(null);
        
        
        
    /**
     * Creates new form AvancesJInternalFrame
     */
    public AvancesJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModificarA1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerAnoR = new javax.swing.JSpinner();
        jSpinnerDiaR = new javax.swing.JSpinner();
        jSpinnerHoraR = new javax.swing.JSpinner();
        jSpinnerMesR = new javax.swing.JSpinner();
        jSpinnerMinutosR = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPropuesta = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerAno = new javax.swing.JSpinner();
        jSpinnerMes = new javax.swing.JSpinner();
        jSpinnerDia = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerMinutos = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonBuscarA = new javax.swing.JButton();
        jButtonModificarA = new javax.swing.JButton();
        jButtonEliminarA = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPorcentaje = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCalificacion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResumen = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCalificacionTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldIdR = new javax.swing.JTextField();
        jButtonBuscarR = new javax.swing.JButton();
        jButtonModificarR = new javax.swing.JButton();
        jButtonEliminarR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButtonModificarA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-file-icon.png"))); // NOI18N
        jButtonModificarA1.setContentAreaFilled(false);
        jButtonModificarA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarA1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Revisión"));

        jLabel9.setText(":");

        jLabel8.setText("Hora:");

        jSpinnerAnoR.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2014), null, Integer.valueOf(2099), Integer.valueOf(1)));

        jSpinnerDiaR.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, Integer.valueOf(31), Integer.valueOf(1)));

        jSpinnerHoraR.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(23), Integer.valueOf(1)));

        jSpinnerMesR.setModel(new javax.swing.SpinnerListModel(new String[] {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}));

        jSpinnerMinutosR.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(59), Integer.valueOf(1)));

        jLabel7.setText("Fecha de Revisión:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Avance"));

        jLabel1.setText("Para la propuesta:");

        jComboBoxPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPropuestaActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de Recepción:");

        jSpinnerAno.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2014), null, Integer.valueOf(2099), Integer.valueOf(1)));

        jSpinnerMes.setModel(new javax.swing.SpinnerListModel(new String[] {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}));

        jSpinnerDia.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, Integer.valueOf(31), Integer.valueOf(1)));

        jLabel3.setText("Hora:");

        jSpinnerHora.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(23), Integer.valueOf(1)));

        jLabel4.setText(":");

        jSpinnerMinutos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(59), Integer.valueOf(1)));

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jLabel5.setText("Descripción:");

        jLabel6.setText("Id:");

        jButtonBuscarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-file-icon.png"))); // NOI18N
        jButtonBuscarA.setContentAreaFilled(false);
        jButtonBuscarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAActionPerformed(evt);
            }
        });

        jButtonModificarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-file-icon.png"))); // NOI18N
        jButtonModificarA.setContentAreaFilled(false);
        jButtonModificarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarAActionPerformed(evt);
            }
        });

        jButtonEliminarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-file-icon.png"))); // NOI18N
        jButtonEliminarA.setContentAreaFilled(false);
        jButtonEliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPropuesta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBuscarA)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jButtonModificarA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEliminarA)
                                .addGap(22, 22, 22)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jSpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jButtonModificarA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEliminarA)
                            .addComponent(jButtonBuscarA))))
                .addContainerGap())
        );

        jLabel10.setText("Porcentaje:");

        jLabel11.setText("Calificación:");

        jTextFieldCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCalificacionActionPerformed(evt);
            }
        });

        jLabel12.setText("Resumen:");

        jTextAreaResumen.setColumns(20);
        jTextAreaResumen.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResumen);

        jLabel13.setText("Calificación Total:");

        jTextFieldCalificacionTotal.setEditable(false);
        jTextFieldCalificacionTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCalificacionTotalActionPerformed(evt);
            }
        });

        jLabel14.setText("Id:");

        jTextFieldIdR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdRActionPerformed(evt);
            }
        });

        jButtonBuscarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-file-icon.png"))); // NOI18N
        jButtonBuscarR.setContentAreaFilled(false);
        jButtonBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarRActionPerformed(evt);
            }
        });

        jButtonModificarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-file-icon.png"))); // NOI18N
        jButtonModificarR.setContentAreaFilled(false);
        jButtonModificarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarRActionPerformed(evt);
            }
        });

        jButtonEliminarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-file-icon.png"))); // NOI18N
        jButtonEliminarR.setContentAreaFilled(false);
        jButtonEliminarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerMesR, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerDiaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerAnoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerHoraR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMinutosR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCalificacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButtonBuscarR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonModificarR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEliminarR))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIdR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(45, 45, 45)
                                .addComponent(jTextFieldPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldIdR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerAnoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMesR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDiaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerHoraR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jSpinnerMinutosR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jTextFieldCalificacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonModificarR)
                        .addComponent(jButtonBuscarR)
                        .addComponent(jButtonEliminarR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-save-icon.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCalificacionActionPerformed

    private void jTextFieldCalificacionTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCalificacionTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCalificacionTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if(jTextFieldIdR.getText().isEmpty()){
                avance.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText())));
                avance.setPropuestasId((Propuestas)jComboBoxPropuesta.getSelectedItem());
                String string =jSpinnerDia.getName()+"/"+jSpinnerMes.getName()+"/"+jSpinnerAno.getName();
                try {
                    Date date = new SimpleDateFormat("dd/MM/yyyy").parse(string);
                    avance.setFechaRecepcion(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora = jSpinnerHora.getName()+" "+jSpinnerMinutos.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora);
                    avance.setHoraRecepcion(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                avance.setDescripcion(jTextAreaDescripcion.getText());
                try {
                    avances.create(avance);
                } catch (Exception ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                               
                
                
            }else if(jTextAreaDescripcion.getText().isEmpty()){
                revision.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldIdR.getText())));
                String string =jSpinnerDiaR.getName()+"/"+jSpinnerMesR.getName()+"/"+jSpinnerAnoR.getName();
                try {
                    Date date = new SimpleDateFormat("dd/MM/yyyy").parse(string);
                    revision.setFechaRevision(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora = jSpinnerHoraR.getName()+" "+jSpinnerMinutosR.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora);
                    revision.setHoraRevision(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                revision.setAvancesId(avances.findAvances(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText()))));
                revision.setResumenObservacion(jTextAreaResumen.getText());
                revision.setPorcentajeAvance(BigDecimal.valueOf(Long.parseLong(jTextFieldPorcentaje.getText())));
                revision.setCalificacionAvance(BigDecimal.valueOf(Double.parseDouble(jTextFieldCalificacion.getText())));
                try {
                    revisiones.create(revision);
                } catch (Exception ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }else{
                avance.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText())));
                avance.setPropuestasId((Propuestas)jComboBoxPropuesta.getSelectedItem());
                String string =jSpinnerDia.getName()+"/"+jSpinnerMes.getName()+"/"+jSpinnerAno.getName();
                try {
                    Date date = new SimpleDateFormat("dd/MM/yyyy").parse(string);
                    avance.setFechaRecepcion(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora = jSpinnerHora.getName()+" "+jSpinnerMinutos.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora);
                    avance.setHoraRecepcion(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                avance.setDescripcion(jTextAreaDescripcion.getText());
                try {
                    avances.create(avance);
                } catch (Exception ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                revision.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldIdR.getText())));
               String string1 =jSpinnerDiaR.getName()+"/"+jSpinnerMesR.getName()+"/"+jSpinnerAnoR.getName();
                try {
                    Date date = new SimpleDateFormat("dd/MM/yyyy").parse(string1);
                    revision.setFechaRevision(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora1 = jSpinnerHoraR.getName()+" "+jSpinnerMinutosR.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora1);
                    revision.setHoraRevision(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                revision.setAvancesId(avance);
                revision.setResumenObservacion(jTextAreaResumen.getText());
                revision.setPorcentajeAvance(BigDecimal.valueOf(Long.parseLong(jTextFieldPorcentaje.getText())));
                revision.setCalificacionAvance(BigDecimal.valueOf(Double.parseDouble(jTextFieldCalificacion.getText())));
                try {
                    revisiones.create(revision);
                } catch (Exception ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                
                // TODO ESTO ES PARA REGISTRAR O UNA REVISIÓN O UN AVANCE O AMBOS...
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPropuestaActionPerformed
            Iterator it = propuestasjpa.findPropuestasEntities().iterator(); 
            while(it.hasNext()){
                Object o = (Propuestas)it.next();
                jComboBoxPropuesta.addItem(o);//lleno el combobox con las propuestas
            }
    }//GEN-LAST:event_jComboBoxPropuestaActionPerformed

    private void jTextFieldIdRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdRActionPerformed

    private void jButtonBuscarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAActionPerformed
            avance = avances.findAvances(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText())));
            jTextAreaDescripcion.setText(avance.getDescripcion());
            jComboBoxPropuesta.setSelectedItem(avance.getPropuestasId());
            // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarAActionPerformed

    private void jButtonModificarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarAActionPerformed
            avance.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText())));
                avance.setPropuestasId((Propuestas)jComboBoxPropuesta.getSelectedItem());
                String string =jSpinnerDia.getName()+"/"+jSpinnerMes.getName()+"/"+jSpinnerAno.getName();
                try {
                    Date date = new SimpleDateFormat("dd/MM/yyyy").parse(string);
                    avance.setFechaRecepcion(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora = jSpinnerHora.getName()+" "+jSpinnerMinutos.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora);
                    avance.setHoraRecepcion(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                avance.setDescripcion(jTextAreaDescripcion.getText());
            try {
                avances.edit(avance);// TODO add your handling code here:
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonModificarAActionPerformed

    private void jButtonEliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAActionPerformed
            
            try {
                avances.destroy(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText())));
           
            } catch (IllegalOrphanException ex) {
                Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonEliminarAActionPerformed

    private void jButtonBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarRActionPerformed
            revision = revisiones.findRevisionesAvance(BigDecimal.valueOf(Long.parseLong(jTextFieldIdR.getText())));
            jTextAreaResumen.setText(revision.getResumenObservacion());
            jTextFieldCalificacion.setText(""+revision.getCalificacionAvance());
            jTextFieldPorcentaje.setText(""+revision.getPorcentajeAvance());// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarRActionPerformed

    private void jButtonModificarA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarA1ActionPerformed

    private void jButtonModificarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarRActionPerformed
                revision.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldIdR.getText())));
                String string =jSpinnerDiaR.getName()+"/"+jSpinnerMesR.getName()+"/"+jSpinnerAnoR.getName();
                try {
                    Date date = new SimpleDateFormat("dd/MM/yyyy").parse(string);
                    revision.setFechaRevision(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora = jSpinnerHoraR.getName()+" "+jSpinnerMinutosR.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora);
                    revision.setHoraRevision(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                revision.setAvancesId(avances.findAvances(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText()))));
                revision.setResumenObservacion(jTextAreaResumen.getText());
                revision.setPorcentajeAvance(BigDecimal.valueOf(Long.parseLong(jTextFieldPorcentaje.getText())));
                revision.setCalificacionAvance(BigDecimal.valueOf(Double.parseDouble(jTextFieldCalificacion.getText())));
            try {
                revisiones.edit(revision);// TODO add your handling code here:
            } catch (Exception ex) {
                Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButtonModificarRActionPerformed

    private void jButtonEliminarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarRActionPerformed
                   // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarA;
    private javax.swing.JButton jButtonBuscarR;
    private javax.swing.JButton jButtonEliminarA;
    private javax.swing.JButton jButtonEliminarR;
    private javax.swing.JButton jButtonModificarA;
    private javax.swing.JButton jButtonModificarA1;
    private javax.swing.JButton jButtonModificarR;
    private javax.swing.JComboBox jComboBoxPropuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerAno;
    private javax.swing.JSpinner jSpinnerAnoR;
    private javax.swing.JSpinner jSpinnerDia;
    private javax.swing.JSpinner jSpinnerDiaR;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JSpinner jSpinnerHoraR;
    private javax.swing.JSpinner jSpinnerMes;
    private javax.swing.JSpinner jSpinnerMesR;
    private javax.swing.JSpinner jSpinnerMinutos;
    private javax.swing.JSpinner jSpinnerMinutosR;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextArea jTextAreaResumen;
    private javax.swing.JTextField jTextFieldCalificacion;
    private javax.swing.JTextField jTextFieldCalificacionTotal;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdR;
    private javax.swing.JTextField jTextFieldPorcentaje;
    // End of variables declaration//GEN-END:variables
}
