/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.jinternals;

import controller.AvancesJpaController;
import controller.PropuestasJpaController;
import controller.RevisionesAvanceJpaController;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Avances;
import modelo.Propuestas;
import modelo.RevisionesAvance;

/**
 *
 * @author Puyo
 */
public class AvancesJInternalFrame extends javax.swing.JInternalFrame {
        Propuestas propuestas = new Propuestas();
        PropuestasJpaController propuestasjpa = new PropuestasJpaController(null);
        Avances avance = new Avances();
        AvancesJpaController avances = new AvancesJpaController(null);
        RevisionesAvance revision = new RevisionesAvance();
        RevisionesAvanceJpaController revisiones = new RevisionesAvanceJpaController(null);
        
        
        
    /**
     * Creates new form AvancesJInternalFrame
     */
    public AvancesJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerAnoR = new javax.swing.JSpinner();
        jSpinnerDiaR = new javax.swing.JSpinner();
        jSpinnerHoraR = new javax.swing.JSpinner();
        jSpinnerMesR = new javax.swing.JSpinner();
        jSpinnerMinutosR = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPropuesta = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerAno = new javax.swing.JSpinner();
        jSpinnerMes = new javax.swing.JSpinner();
        jSpinnerDia = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerMinutos = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPorcentaje = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCalificacion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResumen = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCalificacionTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldIdR = new javax.swing.JTextField();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Revisión"));

        jLabel9.setText(":");

        jLabel8.setText("Hora:");

        jSpinnerAnoR.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2014), null, Integer.valueOf(2099), Integer.valueOf(1)));

        jSpinnerDiaR.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, Integer.valueOf(31), Integer.valueOf(1)));

        jSpinnerHoraR.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(23), Integer.valueOf(1)));

        jSpinnerMesR.setModel(new javax.swing.SpinnerListModel(new String[] {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}));

        jSpinnerMinutosR.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(59), Integer.valueOf(1)));

        jLabel7.setText("Fecha de Revisión:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Avance"));

        jLabel1.setText("Para la propuesta:");

        jComboBoxPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPropuestaActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de Recepción:");

        jSpinnerAno.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2014), null, Integer.valueOf(2099), Integer.valueOf(1)));

        jSpinnerMes.setModel(new javax.swing.SpinnerListModel(new String[] {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}));

        jSpinnerDia.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, Integer.valueOf(31), Integer.valueOf(1)));

        jLabel3.setText("Hora:");

        jSpinnerHora.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(23), Integer.valueOf(1)));

        jLabel4.setText(":");

        jSpinnerMinutos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(59), Integer.valueOf(1)));

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jLabel5.setText("Descripción:");

        jLabel6.setText("Id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPropuesta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jLabel10.setText("Porcentaje:");

        jLabel11.setText("Calificación:");

        jTextFieldCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCalificacionActionPerformed(evt);
            }
        });

        jLabel12.setText("Resumen:");

        jTextAreaResumen.setColumns(20);
        jTextAreaResumen.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResumen);

        jLabel13.setText("Calificación Total:");

        jTextFieldCalificacionTotal.setEditable(false);
        jTextFieldCalificacionTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCalificacionTotalActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Id:");

        jTextFieldIdR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerMesR, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPorcentaje))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jSpinnerDiaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnerAnoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCalificacion)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerHoraR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldIdR)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerMinutosR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCalificacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(198, 198, 198))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerAnoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMesR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDiaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerHoraR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jSpinnerMinutosR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldIdR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCalificacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCalificacionActionPerformed

    private void jTextFieldCalificacionTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCalificacionTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCalificacionTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if(jTextFieldIdR.getText().isEmpty()){
                avance.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText())));
                avance.setPropuestasId((Propuestas)jComboBoxPropuesta.getSelectedItem());
                String string = jSpinnerMes.getName()+" "+jSpinnerDia.getName()+" "+jSpinnerAno.getName();
                try {
                    Date date = new SimpleDateFormat("MM dd yyyy").parse(string);
                    avance.setFechaRecepcion(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora = jSpinnerHora.getName()+" "+jSpinnerMinutos.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora);
                    avance.setHoraRecepcion(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                avance.setDescripcion(jTextAreaDescripcion.getText());
                try {
                    avances.create(avance);
                } catch (Exception ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                               
                
                
            }else if(jTextAreaDescripcion.getText().isEmpty()){
                revision.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldIdR.getText())));
                String string = jSpinnerMesR.getName()+" "+jSpinnerDiaR.getName()+" "+jSpinnerAnoR.getName();
                try {
                    Date date = new SimpleDateFormat("MM dd yyyy").parse(string);
                    revision.setFechaRevision(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora = jSpinnerHoraR.getName()+" "+jSpinnerMinutosR.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora);
                    revision.setHoraRevision(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                revision.setAvancesId(avances.findAvances(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText()))));
                revision.setResumenObservacion(jTextAreaResumen.getText());
                revision.setPorcentajeAvance(BigDecimal.valueOf(Long.parseLong(jTextFieldPorcentaje.getText())));
                revision.setCalificacionAvance(BigDecimal.valueOf(Double.parseDouble(jTextFieldCalificacion.getText())));
                try {
                    revisiones.create(revision);
                } catch (Exception ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }else{
                avance.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldId.getText())));
                avance.setPropuestasId((Propuestas)jComboBoxPropuesta.getSelectedItem());
                String string = jSpinnerMes.getName()+" "+jSpinnerDia.getName()+" "+jSpinnerAno.getName();
                try {
                    Date date = new SimpleDateFormat("MM dd yyyy").parse(string);
                    avance.setFechaRecepcion(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora = jSpinnerHora.getName()+" "+jSpinnerMinutos.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora);
                    avance.setHoraRecepcion(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                avance.setDescripcion(jTextAreaDescripcion.getText());
                try {
                    avances.create(avance);
                } catch (Exception ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                revision.setId(BigDecimal.valueOf(Long.parseLong(jTextFieldIdR.getText())));
                String string1 = jSpinnerMesR.getName()+" "+jSpinnerDiaR.getName()+" "+jSpinnerAnoR.getName();
                try {
                    Date date = new SimpleDateFormat("MM dd yyyy").parse(string1);
                    revision.setFechaRevision(date);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String hora1 = jSpinnerHoraR.getName()+" "+jSpinnerMinutosR.getName();
                try {
                    Date horas = new SimpleDateFormat("HH mm").parse(hora1);
                    revision.setHoraRevision(horas);
                } catch (ParseException ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                revision.setAvancesId(avance);
                revision.setResumenObservacion(jTextAreaResumen.getText());
                revision.setPorcentajeAvance(BigDecimal.valueOf(Long.parseLong(jTextFieldPorcentaje.getText())));
                revision.setCalificacionAvance(BigDecimal.valueOf(Double.parseDouble(jTextFieldCalificacion.getText())));
                try {
                    revisiones.create(revision);
                } catch (Exception ex) {
                    Logger.getLogger(AvancesJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                
                // TODO ESTO ES PARA REGISTRAR O UNA REVISIÓN O UN AVANCE O AMBOS...
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPropuestaActionPerformed
            Iterator it = propuestasjpa.findPropuestasEntities().iterator(); 
            while(it.hasNext()){
                Object o = (Propuestas)it.next();
                jComboBoxPropuesta.addItem(o);//lleno el combobox con las propuestas
            }
    }//GEN-LAST:event_jComboBoxPropuestaActionPerformed

    private void jTextFieldIdRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxPropuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerAno;
    private javax.swing.JSpinner jSpinnerAnoR;
    private javax.swing.JSpinner jSpinnerDia;
    private javax.swing.JSpinner jSpinnerDiaR;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JSpinner jSpinnerHoraR;
    private javax.swing.JSpinner jSpinnerMes;
    private javax.swing.JSpinner jSpinnerMesR;
    private javax.swing.JSpinner jSpinnerMinutos;
    private javax.swing.JSpinner jSpinnerMinutosR;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextArea jTextAreaResumen;
    private javax.swing.JTextField jTextFieldCalificacion;
    private javax.swing.JTextField jTextFieldCalificacionTotal;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdR;
    private javax.swing.JTextField jTextFieldPorcentaje;
    // End of variables declaration//GEN-END:variables
}
