package vista.jinternals;
import controller.ProyectosJpaController;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import modelo.Proyectos;
import vista.MDIAplicacion;

/**
 *
 * @author LuigyMendez
 */
public class ConsultarProyectosJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarProyectosJInternalFrame
     */
    private ProyectosJpaController proyectosJpaController = new ProyectosJpaController();
    Object[][] registrosJTable;

    //Formulario
    private FormularioProyectoJInternalFrame frmProyecto;
    private ConsultarEntregasJInternalFrame consultarEntregas;

    public ConsultarProyectosJInternalFrame() {
        registrosJTable = proyectosJpaController.getMatrizParaJTable();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProyectos = new javax.swing.JTable();
        jButtonRegistrarEntrega = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jToolBar1.setRollover(true);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-save-icon.png"))); // NOI18N
        jButtonGuardar.setFocusable(false);
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGuardar);

        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-file-icon.png"))); // NOI18N
        jButtonModificar.setFocusable(false);
        jButtonModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonModificar);

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-file-icon.png"))); // NOI18N
        jButtonEliminar.setFocusable(false);
        jButtonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonEliminar);

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-file-icon.png"))); // NOI18N
        jButtonBuscar.setFocusable(false);
        jButtonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonBuscar);

        jButtonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apps-pdf-icon.png"))); // NOI18N
        jButtonReportes.setFocusable(false);
        jButtonReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonReportes);

        jTableProyectos.setModel(new javax.swing.table.DefaultTableModel(
            registrosJTable,
            new String [] {
                "Id","Titulo", "Periodo", "Grupo", "Estado", "Nota", "Empresa"
            }
        ));
        jTableProyectos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableProyectos);

        jButtonRegistrarEntrega.setText("Gestionar entregas");
        jButtonRegistrarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEntregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRegistrarEntrega)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistrarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        MDIAplicacion.desktopPane.removeAll();
        frmProyecto = new FormularioProyectoJInternalFrame(null);
        MDIAplicacion.desktopPane.add(frmProyecto);
        frmProyecto.setVisible(true);
    }                                              

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int selectedRow, codigo;
        Proyectos proyecto = null;
        selectedRow = jTableProyectos.getSelectedRow();
        System.out.println("La columna seleccionada es :" + selectedRow);

        try {
            codigo = Integer.parseInt(jTableProyectos.getValueAt(selectedRow, 0).toString()); // Extraigo el dato
            proyecto = proyectosJpaController.findProyectos(new BigDecimal(codigo));
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún elemento");
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún elemento");
        }

        if (selectedRow != -1 && proyecto != null) {
            System.out.println("Llamando la modificacion");
            MDIAplicacion.desktopPane.removeAll();
            frmProyecto = new FormularioProyectoJInternalFrame(proyecto);
            MDIAplicacion.desktopPane.add(frmProyecto);
            frmProyecto.setVisible(true);
        }
    }                                                

    private void jButtonRegistrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {                                                        
      int selectedRow, codigo;
        Proyectos proyecto = null;
        selectedRow = jTableProyectos.getSelectedRow();
        System.out.println("La columna seleccionada es :" + selectedRow);

        try {
            codigo = Integer.parseInt(jTableProyectos.getValueAt(selectedRow, 0).toString()); // Extraigo el dato
            proyecto = proyectosJpaController.findProyectos(new BigDecimal(codigo));
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un proyecto para listar sus entregas");
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un proyecto para listar sus entregas");
        }

        if (selectedRow != -1 && proyecto != null) {
            System.out.println("Llamando la modificacion");
            MDIAplicacion.desktopPane.removeAll();
            consultarEntregas = new ConsultarEntregasJInternalFrame(proyecto);
            MDIAplicacion.desktopPane.add(consultarEntregas);
            consultarEntregas.setVisible(true);
        }
    }                                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegistrarEntrega;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProyectos;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration                   
}